linters:
  enable-all: true
  disable:
    - funlen
    - gocognit
    - godox
    - lll
    - wsl

issues:
  exclude-rules:
    - linters:
        - scopelint
      path: "_test\\.go"
    - linters:
        - gochecknoglobals
      path: internal/generate-testdata